# Generated by Django 4.2.6 on 2023-11-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='time_stamps',
        ),
    ]
